# wandb
wandb_project: fix_bug

unet_input_channels: 4
vae_num_channels: 4

# time sampling 
# TODO : tuning 
timestep_sampling: custom_timesteps
selected_timesteps: [250, 500, 750, 1000]
prob: [0.25, 0.25, 0.25, 0.25]

# loss functions
# TODO : tuning 
pixel_loss_type: lpips # l1 l2
pixel_loss_weight: 10.0
latent_loss_type: l2 # l1 l2
latent_loss_weight: 1.0

# diffusion
bridge_noise_sigma: 0.005
conditioning_images_keys: []
conditioning_masks_keys: []

#data
root_dir: data/filter_ds
train_csv: data/5_folds_split_2D/fold_1_train_2d.csv
val_csv: data/5_folds_split_2D/fold_1_val_2d.csv


# optimizer and learning rate scheduler
# TODO : tuning 
batch_size: 4
learning_rate: 1e-4 
optimizer: Adam

# logs and saves
num_steps: [1, 4]
log_interval: 500
resume_from_checkpoint: true
max_epochs: 50
save_interval: 5000
save_ckpt_path: ./checkpoints
